languageCode = "en-us"
editor = "sublime"
MetaDataFormat = "YAML"
title = "Lucas Roesler"
baseurl = "https://lucasroesler.com/"
theme = "lucas"
canonifyurls = true

[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"

# [outputs]
#   home = ["HTML"]
#   post = ["HTML", "RSS"]

[author]
  name = "Lucas Roesler"
  bio = "I am senior engineer at <a href='https://contiamo.com'>contiamo.com</a> and an ex-mathematician. I have worked on web applications, algorithms for image analysis, machine learning problems, and pure math research."
  job = "Senior Engineer"
  location = "Berlin, DE"
  gravatarEmail = "roesler.lucas@gmail.com"
  # Overwritten by your gravatar image if `author.gravatarEmail` is filled
  picture = "https://cdn1.iconfinder.com/data/icons/ninja-things-1/1772/ninja-simple-512.png"
  # Your Twitter username without the @. E.g : thibaudlepretre
  twitter = "theaxer"


# Menu Configuration
[menu]
  [[menu.main]]
    weight = 1
    identifier = "home"
    name = "Home"
    pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
    url = "/"

  [[menu.main]]
    weight = 2
    identifier = "blog"
    name = "Blog"
    pre = "<i class=\"sidebar-button-icon fa fa-lg fa-quote-right\"></i>"
    url = "/posts"
    [menu.main.params]
      icon = "quote-right"

  [[menu.main]]
    weight = 3
    identifier = "tags"
    name = "Tags"
    url = "/tags"

  [[menu.main]]
    weight = 4
    identifier = "resume"
    name = "Resume"
    url = "/resume/"
    [menu.main.params]
      icon = "file-alt"

  [[menu.links]]
    weight = 1
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/lucasroesler"

  [[menu.links]]
    weight = 3
    identifier = "stackoverflow"
    name = "Stack Overflow"
    url = "https://stackoverflow.com/users/826102/theaxer"
    [menu.links.params]
      icon = "stack-overflow"

  [[menu.links]]
    weight = 2
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/theaxer"

  [[menu.links]]
    weight = 4
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/lucasroesler"

  [[menu.misc]]
    weight = 1
    identifier = "rss"
    name = "RSS"
    url = "/posts/index.xml"

  # additonal links to add to the intro page _after_ the menu.links list
  [[menu.intro]]
    weight = 1
    identifier = "resume"
    name = "Resume"
    url = "/resume/"
    [menu.intro.params]
      iconset = "fas"
      icon = "file-alt"
      text = "CV"

  [[menu.intro]]
    weight = 2
    identifier = "blog"
    name = "Blog"
    url = "/posts"
    [menu.intro.params]
      iconset = "fas"
      text = "blog"

  [[menu.intro]]
    weight = 1
    identifier = "description"
    name = "Description"
    url = "#a-few-more-details"
    [menu.intro.params]
      iconset = "fas"
      icon = "angle-down"
      text = "more"

[params]
  # Customize date format use to render blog post date, categories and other
  # You must use date format used by Go Time package https://golang.org/pkg/time/
  # Months (not work with short month like "jan", "feb", etc) are translated if translation exists on i18n folders
  # Default format is: January 2, 2006
  dateFormat = "2006-01-02"

  # Global keywords configuration. Following keywords will be add to every pages
  keywords = ["development", "management", "python", "django"]
  description = "Talkity talk by Lucas Roesler"

  [params.copyright]
    start = "2017"
  # Customize date format use to render blog post date, categories and other
  # You must use date format used by Go Time package https://golang.org/pkg/time/
  # Months (not work with short month like "jan", "feb", etc) are translated if translation exists on i18n folders
  # Default format is: January 2, 2006
  # dateFormat = "2006-01-02"

  # try https://coolors.co/

  # Gunmetal
  [params.colors]
    background = "#333745"
    foreground = "#edf7ff"
    hover = "#c7efcf"
    svgFillOpacity = "0.25"
    dark = "#5C6B73"

  # Kobe red
  # [params.colors]
      # background = "#872108"
      # foreground = "#edf7ff"
      # hover = "#003e1f"

  [params.posts.colors]
    background = "#ffffff"
    foreground = "#000000"
    hover = "#c7efcf"
    dark = "#0C090D"
